name: drp_nnUNet_v3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=25.0
  - setuptools
  - wheel
  - ca-certificates
  - openssl
  - libffi
  - zlib
  - readline
  - sqlite
  - tk
  - pip:
      # PyTorch packages from PyPI (with specified index-url)
      - torch==2.6.0 --index-url https://download.pytorch.org/whl/cu118
      - torchvision==0.21.0 --index-url https://download.pytorch.org/whl/cu118
      - torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu118

      # Other pip packages
      - fft-conv-pytorch
      - typing_extensions
      - pillow

      # Original pip dependencies
      - acvl-utils==0.2.1
      - argparse==1.4.0
      - blosc2==2.5.1
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - connected-components-3d==3.22.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - dicom2nifti==2.5.1
      - dynamic-network-architectures==0.3.1
      - einops==0.8.1
      - filelock==3.13.1
      - fonttools==4.56.0
      - fsspec==2024.6.1
      - future==1.0.0
      - idna==3.10
      - imagecodecs==2024.12.30
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - linecache2==1.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - msgpack==1.1.0
      - ndindex==1.9.2
      - networkx==3.2.1
      - nibabel==5.3.2
      - numpy==1.26.3
      - packaging==24.2
      - pandas==2.2.3
      - py-cpuinfo==9.0.0
      - pydicom==2.4.4
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-gdcm==3.0.24.1
      - graphviz==0.20.3
      - pytz==2025.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - simpleitk==2.4.1
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - tqdm==4.67.1
      - traceback2==1.4.0
      - triton==3.2.0
      - tzdata==2025.1
      - unittest2==1.1.0
      - urllib3==2.3.0
      - yacs==0.1.8
      - zipp==3.21.0

prefix: /path/to/your/virtual/environment/drp_nnUNet_v3

